### ISSUE TITLE
OBOS settings 

### ISSUE THREAD

**Issue by AdamJGallagher** [wonboyn/traderissues#10]
Need to review the OBOS settings to ensure they are both improving the average trade outcomes and not excessively restricting trading.

**Comment by wonboyn** [comment]
Need more detail on this. What changes need to be made?

**Comment by AdamJGallagher** [comment]
Sorry, I'm not sure. You mentioned that the OBOS was on 14 days? I believe it should be 14 candlesticks or closes. 
I found this video of a guy adding OBOS to his bot. There might be some learning in it if you have time to watch it or atleast the core parts of the approach.[ ](https://www.youtube.com/watch?v=n1cX45_E5FE)

**Comment by AdamJGallagher** [comment]
I wonder (just a thought and not for action at this stage), if given that the EA seemed to entering well (prior to OBOS) and it was the timing of the closing out that was the issue, that we could apply the OBOS and any other additional supporting signals just on the close of the trades?

**Comment by wonboyn** [comment]
Hopefully fixed in the latest build from 12/4
