### ISSUE TITLE
EA giving up too much profit before closing a position

### ISSUE THREAD

**Issue by AdamJGallagher** [wonboyn/traderissues#7]
EA waits too long to close winning positions giving up 40-60% of the profit on each trade.![image](https://github.com/wonboyn/traderissues/assets/165977215/3d6a3d70-25f6-48e3-9ed7-4df659fe09db)

![image](https://github.com/wonboyn/traderissues/assets/165977215/16919026-a281-4707-9c1b-c0628d80a595)

**Comment by AdamJGallagher** [comment]
![image](https://github.com/wonboyn/traderissues/assets/165977215/ce714e4e-cecc-4d9a-a9b6-90bd57cf8c60)![image](https://github.com/wonboyn/traderissues/assets/165977215/b1308828-0666-40fe-9f95-3cd558837f55)

**Comment by AdamJGallagher** [comment]
In several trades, it's gone from a reasonable profit to a loss before closing.![image](https://github.com/wonboyn/traderissues/assets/165977215/f7461853-20d9-478e-a688-17bc959f87a2)

**Comment by AdamJGallagher** [comment]
![image](https://github.com/wonboyn/traderissues/assets/165977215/d6b228e2-5dd3-4997-bf0a-e7c5a2122573)
![image](https://github.com/wonboyn/traderissues/assets/165977215/c4090b54-d250-4509-9a31-8dd7c0211260)
![image](https://github.com/wonboyn/traderissues/assets/165977215/5c1674f5-2bf8-4f67-a8f7-091d9baae632)

**Comment by wonboyn** [comment]
I've been working on adding an over-bought / over-sold check based on the relative strength indicator. It adds the following:
- a buy hurdle parameter (ie the RSI must be < buy hurdle) to open a buy position
- a sell hurdle parameter (ie the RSI must be > sell hurdle) to open a sell position
- hard coded thresholds for over-bought/sold to close out a position

**Comment by wonboyn** [comment]
Done in v0.0.7
